# Node 내장 기능 (1)

<br>

## 1. Module 

```javascript

const odd = '홀수';
const even = '짝수';

module.exports = {
    odd,            // 원래는 odd: odd
    even,
};

```

```javascript

const value = require('./3-1(1)');
console.log(value);     // {odd: '홀수', even: '짝수'}

const {odd, even} = require('./3-1(1)');
console.log(odd, even); // 홀수 짝수

function checkOddOrEven(number) {
    if(number % 2) {
        return odd;
    } else {
        return even;
    }
}

module.exports = checkOddOrEven;
```

```javascript

const { odd, even } = require('./3-1(1)');
const checkNumber = require('./3-1(2)');

function checkStringOddOrEven(str) {
    if(str.length % 2) {
        return odd;
    } else {
        return even;
    }
}

console.log(checkNumber(11));
console.log(checkStringOddOrEven('daldalhada'));

```

<br>

    - module.exports를 사용하여 객체나 함수를 export 할 수 있음
    - require를 사용하여 다른 모듈의 객체나 함수를 import 할 수 있음
    - 불필요한 코드의 중복을 방지할 수 있는 장점이 있음

<br>

    - [참고] ES2015 모듈(자바스크립트 자체 모듈 시스템 문법)
    - Node 내장 기능과 자바스크립트 모듈 기능 둘 다 사용가능함
    - 하지만, 두 개의 기능이 일대일로 대응하는 것은 아님
  
```javascript

import {odd, even} from './3-1(1)';

funtcion checkOddOrEven(num) {
    // 생략
}

export default checkOddOrEven


```

<br>


***

<br>

## 6. 클래스

<br>


```javascript

//EX2015+ 전

var Human = function(type) {
    this.type = type || 'human';
};

// 생성자 메서드(스태틱 메서드)
Human.isHuman = function(human) {
    return human instanceof Human;
}

// 인스턴스 메서드(프로토타입 메서드)
Human.prototype.breathe = function() {
    alert('h-a-a-a-m');
};


//EX2015+ 후

class Human {
    constructor(typpe = 'human') {
        this.type = type;
    }

    static isHuman(human) {
        return human instanceof Human;
    }

    breathe() {
        alert('h-a-a-a-m');
    }
}

```

<br>

    - EX2015+ 전에는 코드가 길어질 수록 서로 연관이 있는 코드라는 것을 확인하기 어려움
    - EX2015+ 후에 클래스를 이용함으로써 더욱 깔끔하게 표현이 가능함

<br>


***

<br>

## 7. Promise

<br>

```javascript

const condition = true;
const promise = new Promise((resolve, reject) => {
    if(condition) {
        resolve('성공');
    } else {
        reject('실패');
    }
});

console.log('Promise 전에 출력');

promise
    .then((message) => {
        console.log(message);
    })
    .catch((error) => {
        console.log(error);
    })
    .finally(()=> {
        console.log('무조건 실행');
    })

```

<br>

    - Promise: 내용이 실행 되었지만 결과를 아직 반환하지 않은 객체
    - Callback Hell을 피하기 위한 해결책
    - Then을 붙이면 결과를 반환힘
    - Resolve: 성공 리턴 값, then으로 연결
    - Reject: 실패 리턴 값, catch로 연결
    - finally 부분은 무조건 실행됨.

<br>

```javascript

const promise1 = Promise.resolve('성공1');
const promise2 = Promise.resolve('성공2');

Promise.all([promise1, promise2])
    .then((result) => {
        console.log(result);
    })
    .catch((error) => {
        console.log(error);
    });

Promise.allSettled([promise1, promise2])
    .then((result) => {
        console.log(result);
    })
    .catch((error) => {
        console.log(error)
    })

```

<br>

    - Promise.resolve(result): 바로 resolve하는 Promise
    - Promise.reject(result): 바로 reject 하는 Promise
    - Promise.all(배열): 여러 개의 Promise를 동시에 실행
    - Promise.allSettled: 실패한 Promise들반 추려냄

<br>

***

<br>

## 8. async/await

<br>


```javascript

function findAndSaveUser(Users) {
    Users.findOne({})
        .then((user) => {
            user.name = 'JS';
            return user.svae();
        })
        .then((user) => {
            return Users.findOne({ gender: 'm' });
        })
        .then((user) => {
            //생략
        })
        .catch((err) => {
            console.log(err);
        })
}

```

<br>

    - 위의 코드도 Callback Hell처럼 then이 쌓이는 Promise Hell이 발생함
    - async/await을 도입해서 코드를 간결하게 할 수 있음
    - ※ async/await도 Promise이기 때문에 return 값이 존재하면 then을 사용해야 함


<br>

```javascript

async function findAndSaveUser(Users) {
    let user = await Users.findOne({});
    user.name = 'JS';
    user = await user.save();
    user = await Users.findOne({ gender: 'm' });
    //생략
}

```

<br>

    - 변수 = await Promise; 인 경우 Promise가 resolve딘 값이 변수에 저장
      (결과값 = then Promise)
    - 변수 await 값; 인 경우 그 값이 변수에 저장
    - await이 then 역할을 함
    - 단, async/await은 Promise의 reject를 처리하는 부분이 없어 try/catch문을 사용함


<br>

```javascript

const promise1 = Promise.resolve('성공1');
const promise2 = Promise.resolve('성공2');

(async () => {
    for await (promise of [promise1, promise2]) {
        console.log(promise);
    }
})();

```

<br>

    - Promise.all 처럼 for await(변수 of Promise 배열)을 지원

<br>

***

<br>